apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-toleration-pod
  name: test-toleration-pod
spec:
  containers:
  - image: nginx
    name: pod
  tolerations:
  - key: "zone"
    operator: "Equal"
    value: "secure"
    effect: "NoSchedule"
  - key: "zone"
    operator: "Exists"
    effect: "NoExecute"
