apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    k8s-app: my-daemonset
spec:
  selector:
    matchLabels:
      name: my-ds
  template:
    metadata:
      labels:
        name: my-ds
    spec:
      containers:
      - name: c1
        image: nginx
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
